#!/usr/bin/env bash
# if [[ -z $STOW_FOLDERS ]]; then
STOW_FOLDERS="scripts, nvim, tmux, fzf, bash"
# fi
#
# if [[ -z $DOTFILES ]]; then
#     DOTFILES=$HOME/.crappydots
# fi
# STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES #$DOTFILES/install

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
    if [[ $folder == "tmux" ]]; then
        ./tmx-plugs
    fi
done
